/* Auto-generated by chipcade. Do not edit. */
#ifndef CHIPCADE_H
#define CHIPCADE_H

/* Pseudo memory views for editor/highlighter compatibility. */
extern unsigned char mem[];
extern unsigned char data[];

/* Raw sprite attribute bytes (maps to SPRITE_RAM + i). */
extern unsigned char sprite_data[];

typedef struct {
    unsigned char x;
    unsigned char y;
    unsigned char tile;
    unsigned char flags;
    unsigned char c0;
    unsigned char c1;
    unsigned char c2;
    unsigned char reserved;
} ChipSprite;
extern ChipSprite sprite[];

/* System constants */
#define VRAM 0x2000
#define VRAM_SIZE 0x6000
#define PALETTE 0x8000
#define SPRITE_RAM 0x8030
#define IO 0x8230
#define IO_INPUT 0x8230
#define IO_LEFT 0x8231
#define IO_RIGHT 0x8232
#define IO_UP 0x8233
#define IO_DOWN 0x8234
#define IO_FIRE 0x8235
#define INPUT_LEFT 0x0001
#define INPUT_RIGHT 0x0002
#define INPUT_UP 0x0004
#define INPUT_DOWN 0x0008
#define INPUT_FIRE 0x0010
#define ROM 0x8330
#define VIDEO_WIDTH 256
#define VIDEO_HEIGHT 192

/* Sprite indices */
#define SPR_CHIPCADE 0

#endif /* CHIPCADE_H */
